@extends('layouts.admin')
@section('title','Data Desa Tahunan')
@push('styles')<style>.admin-year-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.admin-year-card{background:#fff;border:1px solid #e5e7eb;border-radius:20px;padding:22px}.admin-year-chart{min-height:320px}.admin-year-actions{display:flex;gap:7px;flex-wrap:wrap}.admin-year-actions a{padding:8px 10px;border-radius:9px;background:#e8f3f2;color:#0f766e;text-decoration:none;font-weight:700}.admin-year-actions a.dark{background:#0f766e;color:#fff}@media(max-width:900px){.admin-year-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
<div class="admin-page-header"><div><span class="section-label">PENGELOLAAN DATA</span><h1>📅 Data Desa Tahunan</h1><p>Pilih tahun, lihat perkembangan, edit data, atau unduh arsip.</p></div><a class="admin-btn admin-btn-secondary" href="{{ route('data-desa.yearly') }}" target="_blank">Lihat User ↗</a></div>
<div class="admin-category-tabs"><a href="{{ route('admin.data-desa') }}">📊 Ringkasan</a><a class="active" href="{{ route('admin.data-desa.yearly') }}">📅 Data Pertahun</a><a href="{{ route('admin.data-desa.category','penduduk') }}">👥 Penduduk</a><a href="{{ route('admin.data-desa.category','pendidikan') }}">🎓 Pendidikan</a><a href="{{ route('admin.data-desa.category','pekerjaan') }}">💼 Pekerjaan</a><a href="{{ route('admin.data-desa.category','sosial') }}">🤝 Sosial</a><a href="{{ route('admin.data-desa.category','fasilitas') }}">🏫 Fasilitas</a><a href="{{ route('admin.data-desa.category','umur') }}">👶 Umur</a><a href="{{ route('admin.data-desa.category','agama') }}">🕌 Agama</a></div>
<div class="admin-year-card" style="margin-bottom:20px"><div style="display:flex;justify-content:space-between;gap:15px;align-items:end;flex-wrap:wrap"><div><span class="section-label">PERIODE</span><h2>Data Tahun {{ $selectedYear }}</h2></div><div style="display:flex;gap:8px;flex-wrap:wrap"><form method="GET" style="display:flex;gap:8px;align-items:end"><label class="admin-field"><span>Tahun</span><select name="year" onchange="this.form.submit()">@foreach($years as $year)<option value="{{ $year }}" @selected((int)$year===(int)$selectedYear)>{{ $year }}</option>@endforeach</select></label></form><a class="admin-btn admin-btn-secondary" href="{{ route('admin.data-desa.export',['format'=>'csv','year'=>$selectedYear]) }}">⬇ CSV</a><a class="admin-btn admin-btn-secondary" href="{{ route('admin.data-desa.export',['format'=>'pdf','year'=>$selectedYear]) }}">⬇ PDF</a></div></div></div>
<div class="admin-year-grid"><div class="admin-year-card"><span class="section-label">PENDUDUK</span><h2>Perkembangan Penduduk</h2><div id="adminPopChart" class="admin-year-chart"></div></div><div class="admin-year-card"><span class="section-label">KELUARGA</span><h2>KK & Keluarga Miskin</h2><div id="adminFamilyChart" class="admin-year-chart"></div></div></div>
<div class="admin-year-card" style="margin-top:20px"><span class="section-label">ARSIP DATA</span><h2>Data Tersimpan</h2><div style="overflow:auto"><table class="data-table"><thead><tr><th>Tahun</th><th>Penduduk</th><th>KK</th><th>Miskin</th><th>Aksi</th></tr></thead><tbody>@forelse($histories->sortByDesc('tahun') as $h)@php($d=$h->data??[])<tr><td><strong>{{ $h->tahun }}</strong></td><td>{{ number_format((int)($d['total_penduduk']??0),0,',','.') }}</td><td>{{ number_format((int)($d['kepala_keluarga']??0),0,',','.') }}</td><td>{{ number_format((int)($d['keluarga_miskin']??0),0,',','.') }}</td><td><div class="admin-year-actions"><a class="dark" href="{{ route('admin.data-desa',['year'=>$h->tahun]) }}">Edit</a><a href="{{ route('admin.data-desa.category',['category'=>'penduduk','year'=>$h->tahun]) }}">Kategori</a><a href="{{ route('admin.data-desa.export',['format'=>'csv','year'=>$h->tahun]) }}">CSV</a><a href="{{ route('admin.data-desa.export',['format'=>'pdf','year'=>$h->tahun]) }}">PDF</a></div></td></tr>@empty<tr><td colspan="5">Belum ada data tahunan.</td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')<script src="{{ asset('js/data-charts.js') }}"></script><script>DesaCharts.line(document.getElementById('adminPopChart'),@json($histories->sortBy('tahun')->pluck('tahun')->values()),[],[{label:'Penduduk',values:@json($histories->sortBy('tahun')->map(fn($h)=>(int)($h->data['total_penduduk']??0))->values()),color:'#0f766e'}]);DesaCharts.line(document.getElementById('adminFamilyChart'),@json($histories->sortBy('tahun')->pluck('tahun')->values()),[],[{label:'KK',values:@json($histories->sortBy('tahun')->map(fn($h)=>(int)($h->data['kepala_keluarga']??0))->values()),color:'#2563eb'},{label:'Miskin',values:@json($histories->sortBy('tahun')->map(fn($h)=>(int)($h->data['keluarga_miskin']??0))->values()),color:'#db2777'}]);</script>@endpush
