@extends('layouts.app')
@section('title','Data Desa per Tahun')
@section('content')
<section class="page-hero"><div class="container"><span class="section-label">ARSIP STATISTIK</span><h1>📅 Data Desa per Tahun</h1><p>Bandingkan data desa dari tahun ke tahun dan unduh arsip setiap periode.</p></div></section>
<section class="section"><div class="container">
<nav class="data-nav"><a href="{{ route('data-desa') }}">📊 Ringkasan</a><a class="active" href="{{ route('data-desa.yearly') }}">📅 Per Tahun</a><a href="{{ route('data-desa.category','penduduk') }}">👥 Penduduk</a><a href="{{ route('data-desa.category','pendidikan') }}">🎓 Pendidikan</a><a href="{{ route('data-desa.category','pekerjaan') }}">💼 Pekerjaan</a><a href="{{ route('data-desa.category','sosial') }}">🤝 Sosial</a><a href="{{ route('data-desa.category','fasilitas') }}">🏫 Fasilitas</a><a href="{{ route('data-desa.category','umur') }}">👶 Umur</a><a href="{{ route('data-desa.category','agama') }}">🕌 Agama</a></nav>
<div class="data-year-panel"><div><span class="section-label">PILIH PERIODE</span><h2>Data Tahun {{ $selectedYear }}</h2><p>Pilih tahun untuk melihat rincian dan mengunduh data.</p></div><form method="GET" class="data-year-form"><label>Tahun</label><select name="year" onchange="this.form.submit()">@foreach($years as $year)<option value="{{ $year }}" @selected((int)$year===(int)$selectedYear)>{{ $year }}</option>@endforeach</select></form><div class="data-download-buttons"><a class="btn-download" href="{{ route('data-desa.export',['format'=>'csv','year'=>$selectedYear]) }}">⬇ CSV {{ $selectedYear }}</a><a class="btn-download secondary" href="{{ route('data-desa.export',['format'=>'pdf','year'=>$selectedYear]) }}">⬇ PDF {{ $selectedYear }}</a></div></div>
<div class="data-chart-grid" style="margin-top:20px"><div class="data-chart-card"><span class="section-label">PENDUDUK</span><h2>Perkembangan Penduduk</h2><div id="yearPop" class="data-chart-box"></div></div><div class="data-chart-card"><span class="section-label">KELUARGA</span><h2>KK & Keluarga Miskin</h2><div id="yearFamily" class="data-chart-box"></div></div></div>
<div class="data-table-card"><span class="section-label">ARSIP TAHUNAN</span><h2>Daftar Data Tersimpan</h2><div class="data-table-wrapper"><table class="data-table"><thead><tr><th>Tahun</th><th>Penduduk</th><th>KK</th><th>Miskin</th><th>Aksi</th></tr></thead><tbody>@forelse($histories->sortByDesc('tahun') as $h)@php($d=$h->data??[])<tr><td><strong>{{ $h->tahun }}</strong></td><td>{{ number_format((int)($d['total_penduduk']??0),0,',','.') }}</td><td>{{ number_format((int)($d['kepala_keluarga']??0),0,',','.') }}</td><td>{{ number_format((int)($d['keluarga_miskin']??0),0,',','.') }}</td><td><div style="display:flex;gap:7px;flex-wrap:wrap"><a class="btn-download" href="{{ route('data-desa',['year'=>$h->tahun]) }}">Lihat</a><a class="btn-download secondary" href="{{ route('data-desa.export',['format'=>'csv','year'=>$h->tahun]) }}">CSV</a><a class="btn-download secondary" href="{{ route('data-desa.export',['format'=>'pdf','year'=>$h->tahun]) }}">PDF</a></div></td></tr>@empty<tr><td colspan="5"><div class="year-empty">Belum ada data tahunan. Admin perlu menyimpan data terlebih dahulu.</div></td></tr>@endforelse</tbody></table></div></div>
</div></section>
@push('scripts')<script src="{{ asset('js/data-charts.js') }}"></script><script>DesaCharts.line(document.getElementById('yearPop'),@json($histories->sortBy('tahun')->pluck('tahun')->values()),[],[{label:'Total Penduduk',values:@json($histories->sortBy('tahun')->map(fn($h)=>(int)($h->data['total_penduduk']??0))->values()),color:'#0f766e'}]);DesaCharts.line(document.getElementById('yearFamily'),@json($histories->sortBy('tahun')->pluck('tahun')->values()),[],[{label:'KK',values:@json($histories->sortBy('tahun')->map(fn($h)=>(int)($h->data['kepala_keluarga']??0))->values()),color:'#2563eb'},{label:'Miskin',values:@json($histories->sortBy('tahun')->map(fn($h)=>(int)($h->data['keluarga_miskin']??0))->values()),color:'#db2777'}]);</script>@endpush
@endsection
